// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioxdzgnhggyenwlyjphb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveGR6Z25oZ2d5ZW53bHlqcGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTM4MzUsImV4cCI6MjA2NjQ4OTgzNX0.UzRCb6rc75O6FTX0wQ_GdTfUWjf4AARKDc5VDB730cM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);